[tool.poetry]
name = "cfn_guard_rs_hook"
version = "0.2.2"
description = "Works with cloudformation-cli-python-lib to remove duplicate code when creating a CloudFormation registry hook that leverages the library cfn_guard_rs"
authors = ["Kevin DeJong <kddejong@amazon.com>"]

[tool.poetry.dependencies]
python = "^3.7.2"
cloudformation-cli-python-lib = "^2.1.12"
cfn-guard-rs = "^0.2.1"
pyyaml = "~5.4.1"
Jinja2 = "^3.0.0"
jsonpath-rw = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.971"
pylint = "^2.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
